apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
      - name: employee
        image: devops1docker/devops1docker:1.1
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: employee
  namespace: default
spec:
  type: NodePort
  selector:
    app: employee
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
